### ISSUE TITLE
Fix cognoml package

### ISSUE THREAD

**Issue by awm33** [cognoma/machine-learning#57] opened 2016-10-12 02:01 UTC
Trying to run the cognoml package, I found a couple issues.
- The requirements are not in setup.py, so a consumer has to manually install them. I manually installed them by looking at the repo's environment.yml file. The following were needed before the next issue was raised.
  - pandas==0.18.1
  - numpy==1.11.1
  - scikit-learn==0.18.0
  - scipy==0.17.1
  
  Take a look at [https://packaging.python.org/requirements/](https://packaging.python.org/requirements/)
- Looks like cogoml.classifiers is not included in the package

```
>>> from cognoml analysis
  File "<stdin>", line 1
    from cognoml analysis
                        ^
SyntaxError: invalid syntax
>>> from cognoml import analysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amadonna/Documents/ml-workers/env/lib/python3.5/site-packages/cognoml/analysis.py", line 11, in <module>
    from cognoml.classifiers.logistic_regression import grid_search
ImportError: No module named 'cognoml.classifiers'
```

Might have to be included [here](https://github.com/cognoma/machine-learning/blob/master/setup.py#L48).

I'd suggest testing the module in a clean environment.

Installed using `pip install git+git://github.com/cognoma/machine-learning`

**Comment by awm33** [comment] 2016-10-12 02:02
@dhimmel FYI

**Comment by dhimmel** [comment] 2016-10-14 17:12
@awm33 currently we only support installation into the conda environment specified in `environment.yml`. You may be able to get conda as simply as `pip install conda`. Note that conda may supersede your default Python path, but this can be undone.

I will look into also supporting installation via pip when requirements are not yet installed.

Regarding `ImportError: No module named 'cognoml.classifiers'` -- not sure / surprises me. I have never included submodules in the `packages` list in `setup.py`. I am pretty sure that the `__init__.py` in the directory is sufficient. Let me know if this issue persists. Could it be that the package isn't actually installed?

**Comment by jessept** [comment] 2016-10-19 22:14
@dhimmel @awm33 I just did a fresh install 5 minutes ago and was able to replicate the issue w the imports.

The issue is more about providing support for pip v conda and how the virtualenv implementations can differ. There is a note at the bottom of the readme here: https://github.com/cognoma/machine-learning

You need to download, then navigate to the project's root directory and do the pip install there rather than straight from the github site. This will put the project's root directory in your python path and be able to find the package correctly.

For now the best bet is to follow the full readme and use conda. I will create a new issue for adding stronger pip support and close this one out.

**Comment by jessept** [comment] 2016-10-19 22:24
@awm33 @dhimmel I can't close issues, I'll leave this up to you Dan.

**Comment by awm33** [comment] 2016-10-19 22:27
I think you should be able to run pip install and not need to run subsequent command or have a specific environment handler setup. That seems to defeat the purpose of exposing it via setup.py and doesn't seem like real pip support. The environment file in this repo also has requirements which are not used by the module.

Running anaconda on the servers seems like a mess. I'm going to manage the requirements manually in the [worker repo](https://github.com/cognoma/ml-workers). But I do think a working setup.py is the best path.

**Comment by dhimmel** [comment] 2016-10-19 23:18
@awm33, I'll work on making it pip installable in a standard python environment. Will specify `install_requires` in `setup.py`. Should also help with https://github.com/cognoma/machine-learning/issues/61

> Running anaconda on the servers seems like a mess.

As a technicality, we're running conda not anaconda. conda is the package manager, while anaconda is a bundle of scientific computing packages for installation via conda.

If we create a docker would that solve the mess? One nice thing about conda is that it manages more than just python packages, so it really helps with scientific computing where a lot of libraries are outside of python.

**Comment by awm33** [comment] 2016-10-19 23:44
@dhimmel It would be great to have pip install working with the minimal requirements needed for the module.

It looks like you have to use anaconda or miniconda to use conda?

Here's an interesting [article](https://www.continuum.io/blog/developer-blog/anaconda-and-docker-better-together-reproducible-data-science) on using anaconda/miniconda/conda for data science along with some containers.

It looks like Conda is handling system level library version control, so I can see the usefulness there. But unless you use `conda list --explicit` you're only saving python package information, not system libraries.

Docker may also be able to help there, if a docker container is used and references a specific version of the linux base, it should have all same system libraries.

Actually, creating a dockerfile for this repo might be nice. Maybe even two dockerfiles, one with jupyter for interactive usage and one that just uses the module.

**Closed as completed** 2016-10-25 01:03 UTC
