### ISSUE TITLE
Check out this project: TPOT Data Science Assistant

### ISSUE THREAD

**Issue by Suberri** [cognoma/machine-learning#19] opened 2016-07-28 14:59 UTC
I am not sure if the TPOT project is applicable or if it would help but it is an interesting spin on ML
http://rhiever.github.io/tpot/

TPOT is a Python tool that automatically creates and optimizes machine 
learning pipelines using genetic programming.

**Comment by awm33** [comment] 2016-07-28 15:03
That looks pretty cool. It looks like it sits right on top of scikit-learn. I've played with genetic programming. It's great for algorithm parameter optimization. I've even messed around with using it in symbolic regression.

**Comment by cgreene** [comment] 2016-07-28 15:18
I have seen TPOT a number of times over the past year and a half. I think the idea is worthwhile but I continue to have concerns about overfitting. It may be much more severe than a grid search. I think what we may want to do is collect an initial set of queries and then carefully evaluate both for overfitting. It is definitely interesting.

**Comment by dhimmel** [comment] 2016-07-28 15:52
I love the idea of TPOT and we should definitely give it a try. We're currently in the experimental stage -- we want to test as many things as possible to get a better understanding of what works for our data. So let's try lots of sklearn-compatible solutions (such as TPOT).

I'm labeling this a task. @Suberri do you want to take it? I'd suggest starting with [this notebook](https://github.com/dhimmel/machine-learning/blob/84a3271b8a11763616b62316cc589a40608e1852/1.TCGA-MLexample.ipynb) as a template. Maybe name your notebook `TPOT-example.ipynb` and submit a pull request?

**Comment by dhimmel** [comment] 2016-09-12 22:32
Closing this issue as part of a routine cleaning. If anyone has an interest in pursuing TPOT for Cognoma, leave a comment and we can reopen this issue.

**Closed as completed by dhimmel** 2016-09-12 22:32 UTC
Labels: task
